// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceMonitor.Web.Data;

#nullable disable

namespace SiteMonitor.Migrations
{
    [DbContext(typeof(MonitoringContext))]
    [Migration("20260828082946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceMonitor.Web.Models.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOnline = false,
                            Name = "YouTube",
                            TargetUrl = "https://youtube.com"
                        },
                        new
                        {
                            Id = 2,
                            IsOnline = false,
                            Name = "GitHub",
                            TargetUrl = "https://github.com"
                        },
                        new
                        {
                            Id = 3,
                            IsOnline = false,
                            Name = "Reddit",
                            TargetUrl = "https://reddit.com"
                        },
                        new
                        {
                            Id = 4,
                            IsOnline = false,
                            Name = "Discord",
                            TargetUrl = "https://discord.com"
                        },
                        new
                        {
                            Id = 5,
                            IsOnline = false,
                            Name = "ChatGPT",
                            TargetUrl = "https://chatgpt.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
